<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="2" failed="5" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-11-03T14:18:21 IST" name="Default suite" finished-at="2019-11-03T14:18:23 IST" duration-ms="1295">
    <groups>
      <group name="Doublesum">
        <method signature="Testclass.sum()[pri:0, instance:testNg.Testclass@a1cdc6d]" name="sum" class="testNg.Testclass"/>
      </group> <!-- Doublesum -->
      <group name="Arithmetic">
        <method signature="Testclass.DivideByZero()[pri:0, instance:testNg.Testclass@a1cdc6d]" name="DivideByZero" class="testNg.Testclass"/>
        <method signature="Testclass.div()[pri:0, instance:testNg.Testclass@a1cdc6d]" name="div" class="testNg.Testclass"/>
        <method signature="Testclass.mult()[pri:0, instance:testNg.Testclass@a1cdc6d]" name="mult" class="testNg.Testclass"/>
        <method signature="Testclass.pow()[pri:0, instance:testNg.Testclass@a1cdc6d]" name="pow" class="testNg.Testclass"/>
        <method signature="Testclass.sqrt()[pri:0, instance:testNg.Testclass@a1cdc6d]" name="sqrt" class="testNg.Testclass"/>
        <method signature="Testclass.sub()[pri:0, instance:testNg.Testclass@a1cdc6d]" name="sub" class="testNg.Testclass"/>
      </group> <!-- Arithmetic -->
    </groups>
    <test started-at="2019-11-03T14:18:21 IST" name="Default test" finished-at="2019-11-03T14:18:23 IST" duration-ms="1295">
      <class name="testNg.Testclass">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:21 IST" name="setUp" finished-at="2019-11-03T14:18:22 IST" duration-ms="735" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="DivideByZero()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="DivideByZero" finished-at="2019-11-03T14:18:22 IST" duration-ms="7" status="PASS">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[Attempt to divide by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: Attempt to divide by zero
at com.epam.tat.module4.Calculator.div(Calculator.java:34)
at testNg.Testclass.DivideByZero(Testclass.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DivideByZero -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="setUp" finished-at="2019-11-03T14:18:22 IST" duration-ms="83" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="mult()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="mult" finished-at="2019-11-03T14:18:22 IST" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [1.0],
did not expect to find [true] but found [false],
expected [34.0] but found [4.0],
did not expect to find [true] but found [false],
expected [34.0] but found [13.0],
did not expect to find [true] but found [false],
expected [34.0] but found [11.0],
did not expect to find [true] but found [false],
expected [34.0] but found [-16.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [1.0],
did not expect to find [true] but found [false],
expected [34.0] but found [4.0],
did not expect to find [true] but found [false],
expected [34.0] but found [13.0],
did not expect to find [true] but found [false],
expected [34.0] but found [11.0],
did not expect to find [true] but found [false],
expected [34.0] but found [-16.0]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg.Testclass.mult(Testclass.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mult -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="setUp" finished-at="2019-11-03T14:18:22 IST" duration-ms="70" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="pow()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="pow" finished-at="2019-11-03T14:18:22 IST" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [2146.689] but found [2146.6890000000003],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [2.8561000000000005],
did not expect to find [true] but found [false],
expected [34.0] but found [391.3539299999999],
did not expect to find [true] but found [false],
expected [34.0] but found [646990.1834490004],
did not expect to find [true] but found [false],
expected [34.0] but found [571.7870000000001],
did not expect to find [true] but found [false],
expected [34.0] but found [127.69000000000001]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [2146.689] but found [2146.6890000000003],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [2.8561000000000005],
did not expect to find [true] but found [false],
expected [34.0] but found [391.3539299999999],
did not expect to find [true] but found [false],
expected [34.0] but found [646990.1834490004],
did not expect to find [true] but found [false],
expected [34.0] but found [571.7870000000001],
did not expect to find [true] but found [false],
expected [34.0] but found [127.69000000000001]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg.Testclass.pow(Testclass.java:109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pow -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="setUp" finished-at="2019-11-03T14:18:22 IST" duration-ms="66" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="sqrt()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="sqrt" finished-at="2019-11-03T14:18:22 IST" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [3.59165699921359] but found [3.591656999213594],
did not expect to find [true] but found [false],
expected [2.82842712474619] but found [2.8284271247461903],
did not expect to find [true] but found [false],
expected [34.0] but found [1.140175425099138],
did not expect to find [true] but found [false],
expected [34.0] but found [1.816590212458495],
did not expect to find [true] but found [false],
expected [34.0] but found [3.0495901363953815],
did not expect to find [true] but found [false],
expected [34.0] but found [2.8809720581775866],
did not expect to find [true] but found [false],
expected [34.0] but found [3.361547262794322]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [3.59165699921359] but found [3.591656999213594],
did not expect to find [true] but found [false],
expected [2.82842712474619] but found [2.8284271247461903],
did not expect to find [true] but found [false],
expected [34.0] but found [1.140175425099138],
did not expect to find [true] but found [false],
expected [34.0] but found [1.816590212458495],
did not expect to find [true] but found [false],
expected [34.0] but found [3.0495901363953815],
did not expect to find [true] but found [false],
expected [34.0] but found [2.8809720581775866],
did not expect to find [true] but found [false],
expected [34.0] but found [3.361547262794322]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg.Testclass.sqrt(Testclass.java:96)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sqrt -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="setUp" finished-at="2019-11-03T14:18:22 IST" duration-ms="52" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="sub()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="sub" finished-at="2019-11-03T14:18:22 IST" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [-0.09999999999999987],
did not expect to find [true] but found [false],
expected [34.0] but found [1.9],
did not expect to find [true] but found [false],
expected [34.0] but found [7.9],
did not expect to find [true] but found [false],
expected [34.0] but found [6.9],
did not expect to find [true] but found [false],
expected [34.0] but found [-12.700000000000001]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [-0.09999999999999987],
did not expect to find [true] but found [false],
expected [34.0] but found [1.9],
did not expect to find [true] but found [false],
expected [34.0] but found [7.9],
did not expect to find [true] but found [false],
expected [34.0] but found [6.9],
did not expect to find [true] but found [false],
expected [34.0] but found [-12.700000000000001]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg.Testclass.sub(Testclass.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sub -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="setUp" finished-at="2019-11-03T14:18:22 IST" duration-ms="93" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="sum()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="sum" finished-at="2019-11-03T14:18:22 IST" duration-ms="6" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [2.7],
did not expect to find [true] but found [false],
expected [34.0] but found [4.699999999999999],
did not expect to find [true] but found [false],
expected [34.0] but found [10.700000000000001],
did not expect to find [true] but found [false],
expected [34.0] but found [9.700000000000001],
did not expect to find [true] but found [false],
expected [34.0] but found [-9.9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [2.7],
did not expect to find [true] but found [false],
expected [34.0] but found [4.699999999999999],
did not expect to find [true] but found [false],
expected [34.0] but found [10.700000000000001],
did not expect to find [true] but found [false],
expected [34.0] but found [9.700000000000001],
did not expect to find [true] but found [false],
expected [34.0] but found [-9.9]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg.Testclass.sum(Testclass.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sum -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:22 IST" name="setUp" finished-at="2019-11-03T14:18:23 IST" duration-ms="65" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="div()[pri:0, instance:testNg.Testclass@a1cdc6d]" started-at="2019-11-03T14:18:23 IST" name="div" finished-at="2019-11-03T14:18:23 IST" depends-on-methods="testNg.Testclass.DivideByZero" duration-ms="3" status="PASS">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[For input string: "1d/0d"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: For input string: "1d/0d"
at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.base/java.lang.Double.parseDouble(Double.java:543)
at testNg.Testclass.div(Testclass.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- div -->
      </class> <!-- testNg.Testclass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
