<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-Q732QR57" failures="5" tests="7" name="testNg.Testclass" time="1.200" errors="0" timestamp="2019-11-03T14:18:23 IST" skipped="0">
  <testcase classname="testNg.Testclass" name="mult" time="0.079">
    <failure message="The following asserts failed:
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	expected [34.0] but found [1.0],
	did not expect to find [true] but found [false],
	expected [34.0] but found [4.0],
	did not expect to find [true] but found [false],
	expected [34.0] but found [13.0],
	did not expect to find [true] but found [false],
	expected [34.0] but found [11.0],
	did not expect to find [true] but found [false],
	expected [34.0] but found [-16.0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [1.0],
did not expect to find [true] but found [false],
expected [34.0] but found [4.0],
did not expect to find [true] but found [false],
expected [34.0] but found [13.0],
did not expect to find [true] but found [false],
expected [34.0] but found [11.0],
did not expect to find [true] but found [false],
expected [34.0] but found [-16.0]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg.Testclass.mult(Testclass.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mult -->
  <testcase classname="testNg.Testclass" name="pow" time="0.086">
    <failure message="The following asserts failed:
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	expected [2146.689] but found [2146.6890000000003],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	expected [34.0] but found [2.8561000000000005],
	did not expect to find [true] but found [false],
	expected [34.0] but found [391.3539299999999],
	did not expect to find [true] but found [false],
	expected [34.0] but found [646990.1834490004],
	did not expect to find [true] but found [false],
	expected [34.0] but found [571.7870000000001],
	did not expect to find [true] but found [false],
	expected [34.0] but found [127.69000000000001]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [2146.689] but found [2146.6890000000003],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [2.8561000000000005],
did not expect to find [true] but found [false],
expected [34.0] but found [391.3539299999999],
did not expect to find [true] but found [false],
expected [34.0] but found [646990.1834490004],
did not expect to find [true] but found [false],
expected [34.0] but found [571.7870000000001],
did not expect to find [true] but found [false],
expected [34.0] but found [127.69000000000001]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg.Testclass.pow(Testclass.java:109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="testNg.Testclass" name="sub" time="0.098">
    <failure message="The following asserts failed:
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	expected [34.0] but found [-0.09999999999999987],
	did not expect to find [true] but found [false],
	expected [34.0] but found [1.9],
	did not expect to find [true] but found [false],
	expected [34.0] but found [7.9],
	did not expect to find [true] but found [false],
	expected [34.0] but found [6.9],
	did not expect to find [true] but found [false],
	expected [34.0] but found [-12.700000000000001]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [-0.09999999999999987],
did not expect to find [true] but found [false],
expected [34.0] but found [1.9],
did not expect to find [true] but found [false],
expected [34.0] but found [7.9],
did not expect to find [true] but found [false],
expected [34.0] but found [6.9],
did not expect to find [true] but found [false],
expected [34.0] but found [-12.700000000000001]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg.Testclass.sub(Testclass.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase classname="testNg.Testclass" name="sum" time="0.741">
    <failure message="The following asserts failed:
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	expected [34.0] but found [2.7],
	did not expect to find [true] but found [false],
	expected [34.0] but found [4.699999999999999],
	did not expect to find [true] but found [false],
	expected [34.0] but found [10.700000000000001],
	did not expect to find [true] but found [false],
	expected [34.0] but found [9.700000000000001],
	did not expect to find [true] but found [false],
	expected [34.0] but found [-9.9]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [34.0] but found [2.7],
did not expect to find [true] but found [false],
expected [34.0] but found [4.699999999999999],
did not expect to find [true] but found [false],
expected [34.0] but found [10.700000000000001],
did not expect to find [true] but found [false],
expected [34.0] but found [9.700000000000001],
did not expect to find [true] but found [false],
expected [34.0] but found [-9.9]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg.Testclass.sum(Testclass.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- sum -->
  <testcase classname="testNg.Testclass" name="div" time="0.069"/>
  <testcase classname="testNg.Testclass" name="DivideByZero" time="0.072"/>
  <testcase classname="testNg.Testclass" name="sqrt" time="0.055">
    <failure message="The following asserts failed:
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	did not expect to find [true] but found [false],
	expected [3.59165699921359] but found [3.591656999213594],
	did not expect to find [true] but found [false],
	expected [2.82842712474619] but found [2.8284271247461903],
	did not expect to find [true] but found [false],
	expected [34.0] but found [1.140175425099138],
	did not expect to find [true] but found [false],
	expected [34.0] but found [1.816590212458495],
	did not expect to find [true] but found [false],
	expected [34.0] but found [3.0495901363953815],
	did not expect to find [true] but found [false],
	expected [34.0] but found [2.8809720581775866],
	did not expect to find [true] but found [false],
	expected [34.0] but found [3.361547262794322]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
did not expect to find [true] but found [false],
expected [3.59165699921359] but found [3.591656999213594],
did not expect to find [true] but found [false],
expected [2.82842712474619] but found [2.8284271247461903],
did not expect to find [true] but found [false],
expected [34.0] but found [1.140175425099138],
did not expect to find [true] but found [false],
expected [34.0] but found [1.816590212458495],
did not expect to find [true] but found [false],
expected [34.0] but found [3.0495901363953815],
did not expect to find [true] but found [false],
expected [34.0] but found [2.8809720581775866],
did not expect to find [true] but found [false],
expected [34.0] but found [3.361547262794322]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testNg.Testclass.sqrt(Testclass.java:96)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- sqrt -->
</testsuite> <!-- testNg.Testclass -->
