<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPINHYDW0238" ignored="0" name="Test" tests="71" failures="35" timestamp="2019-10-30T17:42:38 IST" time="0.132" errors="0">
  <testcase name="DivideByZero" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="mult" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="mult" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="pow" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="mult" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="pow" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="mult" time="0.007" classname="calculatorTest.TestCalculator"/>
  <testcase name="pow" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="mult" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="pow" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="pow" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="mult" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.0]
at calculatorTest.TestCalculator.mult(TestCalculator.java:37)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- mult -->
  <testcase name="pow" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [2.8561000000000005]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [2.8561000000000005]
at calculatorTest.TestCalculator.pow(TestCalculator.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase name="mult" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [4.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [4.0]
at calculatorTest.TestCalculator.mult(TestCalculator.java:37)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- mult -->
  <testcase name="pow" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [391.3539299999999]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [391.3539299999999]
at calculatorTest.TestCalculator.pow(TestCalculator.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase name="mult" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [13.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [13.0]
at calculatorTest.TestCalculator.mult(TestCalculator.java:37)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- mult -->
  <testcase name="pow" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [646990.1834490004]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [646990.1834490004]
at calculatorTest.TestCalculator.pow(TestCalculator.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase name="mult" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [11.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [11.0]
at calculatorTest.TestCalculator.mult(TestCalculator.java:37)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- mult -->
  <testcase name="pow" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [571.7870000000001]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [571.7870000000001]
at calculatorTest.TestCalculator.pow(TestCalculator.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase name="mult" time="0.015" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [-16.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [-16.0]
at calculatorTest.TestCalculator.mult(TestCalculator.java:37)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- mult -->
  <testcase name="pow" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [127.69000000000001]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [127.69000000000001]
at calculatorTest.TestCalculator.pow(TestCalculator.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase name="sqrt" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sub" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sqrt" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sub" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sqrt" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sub" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sqrt" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sub" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sqrt" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sub" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sqrt" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.140175425099138]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.140175425099138]
at calculatorTest.TestCalculator.sqrt(TestCalculator.java:54)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sqrt -->
  <testcase name="sub" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [-0.09999999999999987]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [-0.09999999999999987]
at calculatorTest.TestCalculator.sub(TestCalculator.java:48)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase name="sqrt" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.816590212458495]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.816590212458495]
at calculatorTest.TestCalculator.sqrt(TestCalculator.java:54)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sqrt -->
  <testcase name="sub" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.9]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.9]
at calculatorTest.TestCalculator.sub(TestCalculator.java:48)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase name="sqrt" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [3.0495901363953815]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [3.0495901363953815]
at calculatorTest.TestCalculator.sqrt(TestCalculator.java:54)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sqrt -->
  <testcase name="sub" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [7.9]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [7.9]
at calculatorTest.TestCalculator.sub(TestCalculator.java:48)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase name="sqrt" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [2.8809720581775866]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [2.8809720581775866]
at calculatorTest.TestCalculator.sqrt(TestCalculator.java:54)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sqrt -->
  <testcase name="sub" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [6.9]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [6.9]
at calculatorTest.TestCalculator.sub(TestCalculator.java:48)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase name="sqrt" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [3.361547262794322]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [3.361547262794322]
at calculatorTest.TestCalculator.sqrt(TestCalculator.java:54)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sqrt -->
  <testcase name="sub" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [-12.700000000000001]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [-12.700000000000001]
at calculatorTest.TestCalculator.sub(TestCalculator.java:48)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase name="sum" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="tg" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sum" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="tg" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sum" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="tg" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sum" time="0.016" classname="calculatorTest.TestCalculator"/>
  <testcase name="tg" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sum" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="tg" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="sum" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [2.7]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [2.7]
at calculatorTest.TestCalculator.sum(TestCalculator.java:27)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sum -->
  <testcase name="sum" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [4.699999999999999]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [4.699999999999999]
at calculatorTest.TestCalculator.sum(TestCalculator.java:27)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sum -->
  <testcase name="tg" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [4.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [4.0] but found [1.0]
at calculatorTest.TestCalculator.tg(TestCalculator.java:66)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- tg -->
  <testcase name="sum" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [10.700000000000001]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [10.700000000000001]
at calculatorTest.TestCalculator.sum(TestCalculator.java:27)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sum -->
  <testcase name="tg" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.0]
at calculatorTest.TestCalculator.tg(TestCalculator.java:66)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- tg -->
  <testcase name="sum" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [9.700000000000001]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [9.700000000000001]
at calculatorTest.TestCalculator.sum(TestCalculator.java:27)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sum -->
  <testcase name="tg" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.0]
at calculatorTest.TestCalculator.tg(TestCalculator.java:66)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- tg -->
  <testcase name="sum" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [-9.9]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [-9.9]
at calculatorTest.TestCalculator.sum(TestCalculator.java:27)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sum -->
  <testcase name="tg" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.0]
at calculatorTest.TestCalculator.tg(TestCalculator.java:66)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- tg -->
  <testcase name="div" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="tg" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.0]
at calculatorTest.TestCalculator.tg(TestCalculator.java:66)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- tg -->
  <testcase name="div" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="div" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="div" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="div" time="0.0" classname="calculatorTest.TestCalculator"/>
  <testcase name="div" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [0.9285714285714287]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [0.9285714285714287]
at calculatorTest.TestCalculator.div(TestCalculator.java:43)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase name="div" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [2.357142857142857]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [2.357142857142857]
at calculatorTest.TestCalculator.div(TestCalculator.java:43)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase name="div" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [6.642857142857144]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [6.642857142857144]
at calculatorTest.TestCalculator.div(TestCalculator.java:43)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase name="div" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [5.92857142857143]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [5.92857142857143]
at calculatorTest.TestCalculator.div(TestCalculator.java:43)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase name="div" time="0.0" classname="calculatorTest.TestCalculator">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [-8.071428571428573]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [-8.071428571428573]
at calculatorTest.TestCalculator.div(TestCalculator.java:43)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- div -->
</testsuite> <!-- Test -->
