<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-Q732QR57" failures="1" tests="6" name="testcases.TC002_Get_Single_Employee_Data" time="0.109" errors="0" timestamp="2019-12-08T21:46:38 IST" skipped="3">
  <testcase classname="testcases.TC002_Get_Single_Employee_Data" name="CheckResponseTime" time="0.030"/>
  <testcase classname="testcases.TC002_Get_Single_Employee_Data" name="CheckResponseBody" time="0.003">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at testcases.TC002_Get_Single_Employee_Data.CheckResponseBody(TC002_Get_Single_Employee_Data.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- CheckResponseBody -->
  <testcase classname="testcases.TC002_Get_Single_Employee_Data" name="CheckResponseBody" time="0.062">
    <skipped/>
  </testcase> <!-- CheckResponseBody -->
  <testcase classname="testcases.TC002_Get_Single_Employee_Data" name="CheckResponseBody" time="0.004">
    <skipped/>
  </testcase> <!-- CheckResponseBody -->
  <testcase classname="testcases.TC002_Get_Single_Employee_Data" name="CheckResponseBody" time="0.003">
    <skipped/>
  </testcase> <!-- CheckResponseBody -->
  <testcase classname="testcases.TC002_Get_Single_Employee_Data" name="CheckStatusCode" time="0.007"/>
</testsuite> <!-- testcases.TC002_Get_Single_Employee_Data -->
